site_name: Katalog Fauzan My ID
nav:
    - Home: index.md
    - Zeeida:
       - Aroma Terapi: zeeida/zeeida-aroma-terapi.md
       - Minyak Telon: zeeida/zeeida-minyak-telon.md
       - Minyak Kayu Putih Premium: zeeida/zeeida-minyak-kayu-putih-premium.md
       - Moeza Oil: zeeida/zeeida-moeza-oil.md
       - Bidara Body Wash: zeeida/zeeida-bidara-body-wash.md
       - Sabun Ruqyah: zeeida/zeeida-sabun-ruqyah.md
       - Vico: zeeida/zeeida-vico.md
       

theme: readthedocs